# Generated by Django 3.1 on 2020-08-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='church',
            name='former_religion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='name_of_church',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='residential_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='surname',
            field=models.CharField(max_length=30),
        ),
    ]
