# Generated by Django 3.1 on 2020-08-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0006_auto_20200820_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='birthday',
        ),
        migrations.AddField(
            model_name='church',
            name='county_ssaza',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='district',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='lc1_village',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='lc2_muluka',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='lc3_subcounty',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
