# Generated by Django 3.1 on 2020-08-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0008_auto_20200820_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='marital_status',
        ),
    ]
