# Generated by Django 3.1 on 2020-08-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0010_church_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='children',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='baptised',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='born_again',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='county_ssaza',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='district',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='former_religion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='lc1_village',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='lc2_muluka',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='lc3_subcounty',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='photo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='postal_address',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='residential_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='spirit_filled',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
