# Generated by Django 3.1 on 2020-08-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0012_auto_20200821_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='other_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='scanned_document',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
