# Generated by Django 3.1 on 2020-08-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0013_auto_20200821_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='scanned_document',
        ),
    ]
