# Generated by Django 3.1 on 2020-08-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0015_remove_church_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='scanned_document',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
