# Generated by Django 3.1 on 2020-08-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0016_church_scanned_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
