# Generated by Django 3.1 on 2020-08-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0018_auto_20200821_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='marital_status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
