# Generated by Django 3.1 on 2020-08-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0019_auto_20200821_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='marital_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
