# Generated by Django 3.1 on 2020-08-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0020_auto_20200821_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='registration_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
