# Generated by Django 3.1 on 2020-08-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0022_auto_20200825_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
