# Generated by Django 3.1 on 2020-08-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0023_church_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
