# Generated by Django 3.1.1 on 2020-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0025_auto_20200826_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='registration_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
