# Generated by Django 3.1.1 on 2020-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0026_auto_20200908_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='registration_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
