# Generated by Django 3.1.1 on 2020-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0027_auto_20200908_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='scanned_document',
            field=models.FileField(blank=True, max_length=25, null=True, upload_to='media'),
        ),
    ]
