# Generated by Django 3.1.1 on 2020-09-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0029_auto_20200930_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='scanned_document',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
    ]
