# Generated by Django 3.1.1 on 2020-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0030_auto_20200930_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='scanned_document',
            new_name='doc1',
        ),
        migrations.AddField(
            model_name='church',
            name='doc2',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='doc3',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
    ]
