# Generated by Django 3.1.1 on 2020-10-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0031_auto_20200930_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='doc1',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='church',
            name='doc2',
        ),
        migrations.RemoveField(
            model_name='church',
            name='doc3',
        ),
    ]
