# Generated by Django 3.1.1 on 2020-10-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0032_auto_20201002_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='photo',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
