# Generated by Django 3.1.3 on 2020-11-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0033_auto_20201002_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='document',
        ),
        migrations.CreateModel(
            name='AddDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='scanned_documents')),
                ('doc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Regapp.church')),
            ],
        ),
    ]
