# Generated by Django 3.1.3 on 2020-11-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0034_auto_20201109_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddocument',
            old_name='document',
            new_name='addDoc',
        ),
        migrations.AddField(
            model_name='church',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
    ]
