# Generated by Django 3.1.3 on 2020-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0035_auto_20201109_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='document4',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='document5',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='document6',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='document7',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='document8',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
        migrations.AddField(
            model_name='church',
            name='document9',
            field=models.FileField(blank=True, null=True, upload_to='scanned_documents'),
        ),
    ]
