# Generated by Django 3.1.3 on 2020-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0036_auto_20201110_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document4',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document5',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document6',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document7',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document8',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='church',
            name='document9',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
    ]
