# Generated by Django 3.1.3 on 2020-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0037_auto_20201110_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='alive_parents',
            new_name='father_alive',
        ),
        migrations.AddField(
            model_name='church',
            name='mother_alive',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
