# Generated by Django 3.1.3 on 2020-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0038_auto_20201120_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='church_county',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='church_district',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='church_lc1',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='parents_names',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='church_lc2',
            new_name='head_name',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='church_lc3',
            new_name='head_number',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='church_police',
            new_name='highest_level_of_education',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='membership_size',
            new_name='home_district',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document2',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document3',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document4',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document5',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document6',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document7',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document8',
        ),
        migrations.RemoveField(
            model_name='church',
            name='document9',
        ),
        migrations.RemoveField(
            model_name='church',
            name='name_of_church',
        ),
        migrations.AddField(
            model_name='church',
            name='home_lc1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='home_village',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='occupation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='zone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='AddDocument',
        ),
    ]
