# Generated by Django 3.1.3 on 2020-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0040_auto_20201121_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='home_subcounty',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
